language: generic
cache:
  directories:
  - vendor
sudo: required
services:
- docker
install:
- make bootstrap
script:
- make build test
deploy:
  provider: script
  script: _scripts/deploy.sh
  on:
    branch: master
