apiVersion: v1
kind: Service
metadata:
  name: kubehttpbin
  namespace: kubehttpbin
  labels:
    app: kubehttpbin
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: kubehttpbin
